name: "ARIAC documentation"

on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: usnistgov/Docs4NIST@0.8
        with:
          docs-folder: docs/
          formats: ''
          pip-requirements: requirements.txt
          build-html-command: make html
          insert-header-footer: true
          hidden: false
          
